# Generated by Django 6.0.4 on 2026-05-23 12:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('add_context', 'Add Context'), ('add_constraints', 'Add Constraints'), ('add_format', 'Add Format'), ('add_role', 'Add Role'), ('add_examples', 'Add Examples'), ('restructure', 'Restructure'), ('clarify', 'Clarify'), ('expand', 'Expand')], db_index=True, max_length=50)),
                ('trigger_pattern', models.TextField(help_text='Regex pattern that triggers this rule')),
                ('action_template', models.TextField(help_text='Template for the enhancement action')),
                ('priority', models.IntegerField(default=0)),
                ('applicable_intents', models.JSONField(default=list, help_text='List of intents this rule applies to. Empty = all.')),
                ('applicable_domains', models.JSONField(default=list, help_text='List of domains this rule applies to. Empty = all.')),
                ('is_active', models.BooleanField(default=True)),
                ('success_rate', models.FloatField(default=0.0)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_role', models.TextField(blank=True)),
                ('default_constraints', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Prompt Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('intent', models.CharField(db_index=True, max_length=100)),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('template_body', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('avg_quality_improvement', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-avg_quality_improvement'],
                'unique_together': {('intent', 'domain', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('original_prompt', models.TextField()),
                ('enhanced_prompt', models.TextField()),
                ('enhancement_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('detected_intent', models.CharField(max_length=100)),
                ('detected_domain', models.CharField(max_length=100)),
                ('detected_task_type', models.CharField(max_length=100)),
                ('complexity_level', models.CharField(default='medium', max_length=50)),
                ('original_quality_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('enhanced_quality_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('improvement_delta', models.FloatField(default=0.0)),
                ('original_scores_detail', models.JSONField(default=dict)),
                ('enhanced_scores_detail', models.JSONField(default=dict)),
                ('validation_passed', models.BooleanField(default=True)),
                ('validation_issues', models.JSONField(default=list)),
                ('validation_warnings', models.JSONField(default=list)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('enhancement_method', models.CharField(default='rule_based', max_length=50)),
                ('pipeline_stages_completed', models.JSONField(default=list)),
                ('rules_applied', models.JSONField(default=list)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['detected_intent', 'detected_domain'], name='enhancer_pr_detecte_062f2c_idx'), models.Index(fields=['enhancement_level'], name='enhancer_pr_enhance_f0a706_idx')],
            },
        ),
    ]
