# Generated by Django 6.0.4 on 2026-05-31 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0004_paymentorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', '-created_at'], name='payment_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', '-created_at'], name='payment_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='promptasset',
            index=models.Index(fields=['user', '-updated_at'], name='asset_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='promptasset',
            index=models.Index(fields=['project', '-updated_at'], name='asset_project_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='promptasset',
            index=models.Index(condition=models.Q(('is_public', True)), fields=['is_public', '-created_at'], name='asset_public_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prompthistory',
            index=models.Index(fields=['user', '-created_at'], name='history_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='promptproject',
            index=models.Index(fields=['user', '-updated_at'], name='project_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=models.Index(fields=['asset', '-version_number'], name='version_asset_number_idx'),
        ),
    ]
